version: '3.8'

services:
  falkordb:
    image: falkordb/falkordb:latest
    ports:
      - "6379:6379"
    volumes:
      - falkordb_data:/data

  knowledge_graph_generator:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    volumes:
      - ../data:/app/data
    depends_on:
      - falkordb
    environment:
      - FALKORDB_HOST=falkordb
      - FALKORDB_PORT=6379

volumes:
  falkordb_data: